CREATE TABLE recipro_favorites (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userid INTEGER REFERENCES recipro_users(id) ON DELETE CASCADE NOT NULL,
    recipeid TEXT NOT NULL,
    recipeimage TEXT NOT NULL,
    recipetitle TEXT NOT NULL
);